[package]
name = "rust_mpc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
